project:
  type: website
  output-dir: docs

website:
  title: "LSE GV330"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - readings.qmd
      - seminars.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



