project:
  type: website
  output-dir: docs

website:
  title: "LSE GV330"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - introduction.qmd
      - topic1.qmd
      - topic2.qmd
      - topic3.qmd
      - topic4.qmd
      - topic5.qmd



format:
  html:
    theme: 
      light: spacelab
      dark: superhero
    css: styles.css
    toc: true
    font-family: sans-serif



