project:
  type: website
  output-dir: docs

website:
  title: "LSE GV330"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - readings.qmd
      - seminars.qmd
      - assignments.qmd

format:
  html:
    theme: 
      light: spacelab
      dark: superhero
    css: styles.css
    toc: true
    font-family: sans-serif



